(deffacts initial
    ; Note with the equivalent number
    (note C -9)
    (note C# -8)
    (note Db -8)
    (note D -7)
    (note D# -6)
    (note Eb -6)
    (note E -5)
    (note Fb -5)
    (note F -4)
    (note F# -3)
    (note Gb -3)
    (note G -2)
    (note G# -1)
    (note Ab -1)
    (note A 0)
    (note A# 1)
    (note Bb 1)
    (note B 2)
)